package config

import (
	"os"

	"github.com/joho/godotenv"
)

type EnvKey string

const (
	PORT        EnvKey = "PORT"
	DB_PATH     EnvKey = "DB_PATH"
	MAC_ADDRESS EnvKey = "MAC_ADDRESS"

	// Exchange Broker
	EXCHANGE_DIRECT EnvKey = "EXCHANGE_DIRECT"
	EXCHANGE_TOPIC  EnvKey = "EXCHANGE_TOPIC"

	// RMQ Local
	RMQ_LOCAL_URI        EnvKey = "RMQ_URI"
	RMQ_LOCAL_INSTANCE   EnvKey = "RMQ_HIOTO_LOCAL_INSTANCE"
	SENSOR_QUEUE         EnvKey = "SENSOR_QUEUE"
	AKTUATOR_QUEUE       EnvKey = "AKTUATOR_QUEUE"
	AKTUATOR_ROUTING_KEY EnvKey = "AKTUATOR_ROUTING_KEY"
	MONITORING_QUEUE     EnvKey = "MONITORING_QUEUE"

	// RMQ Cloud
	RMQ_CLOUD_URI             EnvKey = "RMQ_URI"
	RMQ_CLOUD_INSTANCE        EnvKey = "RMQ_HIOTO_CLOUD_INSTANCE"
	REGISTER_RES_CLOUD        EnvKey = "REGISTER_RES_CLOUD"
	UPDATE_RES_CLOUD          EnvKey = "UPDATE_RES_CLOUD"
	DELETE_RES_CLOUD          EnvKey = "DELETE_RES_CLOUD"
	CONTROL_ROUTING_KEY       EnvKey = "CONTROL_ROUTING_KEY"
	REGISTRATION_ROUTING_KEY  EnvKey = "REGISTRATION_ROUTING_KEY"
	UPDATE_DEVICE_ROUTING_KEY EnvKey = "UPDATE_DEVICE_ROUTING_KEY"
	DELETE_DEVICE_ROUTING_KEY EnvKey = "DELETE_DEVICE_ROUTING_KEY"
	RULES_RESPONSE_QUEUE      EnvKey = "RULES_RESPONSE_QUEUE"

	// MQTT Local
	MQTT_LOCAL_HOST          EnvKey = "MQTT_LOCAL_HOST"
	MQTT_LOCAL_USERNAME      EnvKey = "MQTT_LOCAL_USERNAME"
	MQTT_LOCAL_PASSWORD      EnvKey = "MQTT_LOCAL_PASSWORD"
	MQTT_LOCAL_CLIENT_ID     EnvKey = "MQTT_LOCAL_CLIENT_ID"
	MQTT_LOCAL_INSTANCE_NAME EnvKey = "MQTT_LOCAL_INSTANCE_NAME"

	// MQTT Cloud
	MQTT_CLOUD_HOST          EnvKey = "MQTT_CLOUD_HOST"
	MQTT_CLOUD_USERNAME      EnvKey = "MQTT_CLOUD_USERNAME"
	MQTT_CLOUD_PASSWORD      EnvKey = "MQTT_CLOUD_PASSWORD"
	MQTT_CLOUD_CLIENT_ID     EnvKey = "MQTT_CLOUD_CLIENT_ID"
	MQTT_CLOUD_INSTANCE_NAME EnvKey = "MQTT_CLOUD_INSTANCE_NAME"
)

func Load() error {
	return godotenv.Load(".env")
}

func (e EnvKey) GetValue() string {
	return os.Getenv(string(e))
}
